### ISSUE TITLE
how to setting universal-redux.config.js

### ISSUE THREAD

**Issue by sexyoung** [bdefore/redux-universal-renderer#71]
excuse me, I git clone
https://github.com/bdefore/universal-redux-starter

to setting config/universal-redux.config.js
https://github.com/bdefore/universal-redux/blob/master/config%2Funiversal-redux.config.js

I modify it some attributes(head, body ... etc), and I `npm run dev`

but it's not change anything.
so how can I do something?

Thanks!

**Comment by bdefore** [comment]
@sexyoung UR is not a boilerplate. When you clone this repo and run `npm run dev` that's actually meant to be used for local development, customization of UR. For most uses, it's meant to be added as a dependency of your project, and you shouldn't need to modify anything. See the minimal starter example repo: https://github.com/bdefore/universal-redux-starter

**Comment by sexyoung** [comment]
thank you
so, if I wanto change some attributes, ex: 
- custom head
- custom body
- custom html

how can I do?

**Comment by bdefore** [comment]
@sexyoung this should cover it https://github.com/bdefore/universal-redux#adding-your-own-items-to-html-head

**Comment by sexyoung** [comment]
I add file at /src/containers/Head/Head.js,
and fill it refer
https://github.com/bdefore/universal-redux-jwt/blob/master/src/containers/Head/Head.js

and how can I setting `html.root`? universal-redux.config.js?

**Comment by sexyoung** [comment]
sorry, I try to setting /config/universal-redux-config.js
and setting head and body path in html, like this:

``` js
...
  html: {
    head: sourceRoot + '/containers/Head/Head.js',
    body: sourceRoot + '/containers/Body/Body.js',
  }
...
```

the head is work! and body is not. :cry:

**Comment by bdefore** [comment]
@sexyoung if you need the body as well you'll need to use `html.root` which encompasses both the head and the body.

**Comment by cmcewen** [comment]
I'm also having a few issues with this - setting `verbose: false` doesn't seem to have any effect. I'm looking into it now but I believe there's an error when merging the two config files

**Comment by cmcewen** [comment]
The first 2 times this function is called https://github.com/bdefore/universal-redux/blob/master/bin/merge-configs.js#L26 `userConfig` is a function (like the one defined in the sample project), however the next 4 times it is an object.

Making these two changes fixes that problem and loads the config correctly, but this basically assumes that the root path stays the same: https://gist.github.com/cmcewen/9f0cb3d8305b839eed99 https://gist.github.com/cmcewen/96855ae470eac6bd51a7

Definitely not up to speed 100% with what is going on here, but I think things would definitely be simplified if the root path was set in stone.

**Comment by bdefore** [comment]
@cmcewen i've been considering fixing `projectRoot` and `sourceRoot` as a solution to #36 ... previously universal-redux could live outside of node_modules and that's why those needed to be configurable. but that's no longer intended to be the case. also, #7 forces sourceRoot to be `/src` ... perhaps it's best just to have that be a firm requirement for the 3.0.0 release.

**Comment by cmcewen** [comment]
@bdefore that sounds reasonable to me - think it's definitely worth the tradeoff in this case on where to put files to get the benefit of a simple setup

**Comment by bdefore** [comment]
@cmcewen Project root is now fixed as of 3.0.0-rc27. Can your changes be removed successfully and have it respect the `verbose` flag? Note that `verbose` does not turn off all log output. The main reduction is currently to not log out Webpack config. If you'd like that to be more quiet, please file another issue.

**Comment by cmcewen** [comment]
Yeah I know that it still prints the config file, but the difference is whether you get the babelrc, webpack config, and isomorphic tools config.

I still have the same issue using `3.0.0-rc27` - if you add a `console.log(userConfig);` to line 27 of `merge-configs.js` you should be able to see what's happening. `merge-config` needs to be called with the result of the `user-config` function in `server_es6.js` + `webpack-dev-server_es6.js`, not the function itself.

**Comment by bdefore** [comment]
Perhaps I'm not understanding but what's being exported from `user-config` is the output of `getConfig()`. That should be correct?

https://github.com/bdefore/universal-redux/blob/master/bin/user-config.js#L18
https://github.com/bdefore/universal-redux/blob/master/bin/webpack-dev-server_es6.js#L6
https://github.com/bdefore/universal-redux/blob/master/bin/server_es6.js#L10

When testing against universal-redux-jwt, If I add the log you are describing, I see it logging out correctly, apart from one case where the userConfig is `{ verbose: false }` which is the situation where no user config is provided and that is appended to an empty object coming out of user-config.

**Comment by cmcewen** [comment]
I just ran a fresh clone of the starter repo, and ran `npm install`

First time, no config file, ran `npm run dev` - saw verbose logging
2nd time, added this config file, ran `npm run dev` - saw verbose logging, even though it's turned off

``` javascript
module.exports = (projectRoot, sourceRoot) => {
  return {
    verbose: false
  };
};
```

3rd time, made the two modifications in the gists above, which finally resulted in the expected behavior.

Here's my output
https://gist.github.com/cmcewen/10ac135cf3723ce5743e

I originally ran into this problem by trying to modify the html.head and not seeing the modification show up, which I believe is the same problem reported in this issue - are you able to modify that successfully?

**Comment by cmcewen** [comment]
You're right that `getConfig()` is being loaded but the file loaded here (https://github.com/bdefore/universal-redux/blob/master/bin/user-config.js#L3) at least in the sample is a function, not an object

**Comment by bdefore** [comment]
I believe the issue is that you are creating a project configuration file which is itself returning a function. The previously mentioned issue was filed by someone having a similar problem, because the documentation incorrectly mentions copying the annotated example, which (pre rc27) was itself returning a function. Previously it was just an object.

Now, with project and source root fixed, you just need to return an object. You can follow the structure of either the annotated example in universal-redux (no longer returning a function) or the JWT example here: https://github.com/bdefore/universal-redux-jwt/blob/master/config/universal-redux.config.js

Or following your example:

```
module.exports = (projectRoot, sourceRoot) => {
  return {
    verbose: false
  };
};
```

should be:

```
module.exports = {
  verbose: false
};
```

**Comment by cmcewen** [comment]
Ahhhhhhh, make sense - I misread and thought you were going to keep it a function, but just always fix projectRoot and sourceRoot.

Thanks for the fix! You can probably close this issue out then.

This is semi related but have you thought about allowing absolute paths on imports?(/is there a way to do that I'm not aware of?) 

I'm mostly working in React Native now and one nice convention on their packager is the ability to [specify absolute paths](https://github.com/facebook/react-native/issues/3099#issuecomment-155628204) so one could just write `head: 'MyApp/src/components/Head.js'` where `MyApp` is the name of the root directory of the project. That way there wouldn't be a need for getting the sourceRoot or projectRoot.

**Comment by bdefore** [comment]
Now that they are fixed, UR could take on the onus of prepending paths which would get you to `head: '/src/components/Head.js'` ... I suppose that might be better, but if people are copying the annotated example they have the `projectRoot` and `sourceRoot` already.

I expect you didn't mean import statements in your component code? `import Head from 'components'` will work as long as you have an index.js that exports it as a default.
